#!/usr/bin/env python3
"""
Build a searchable skill index with inlined English descriptions.

Input:
  - data/skills_index.json (generated by the crawler)
  - description_en.txt files already generated under data/skills-md/**/description_en.txt

Output:
  - data/skills_search_index.json

Design goals:
  - Fast lookup by id (map keyed by full skill id)
  - Deterministic output ordering for clean diffs
  - No external dependencies
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
INDEX_PATH = DATA_DIR / "skills_index.json"
OUTPUT_PATH = DATA_DIR / "skills_search_index.json"

# Safety cap: descriptions should be short, but avoid accidental huge payloads.
MAX_DESCRIPTION_CHARS = 5000


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _read_text_repo_relative(repo_relative_path: Optional[str]) -> str:
    if not repo_relative_path:
        return ""
    rel = str(repo_relative_path).lstrip("/").strip()
    if not rel:
        return ""
    p = REPO_ROOT / rel
    try:
        return p.read_text(encoding="utf-8", errors="ignore")[:MAX_DESCRIPTION_CHARS].strip()
    except Exception:
        return ""


def _as_str(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, str):
        return v
    return str(v)


def main() -> None:
    if not INDEX_PATH.exists():
        raise SystemExit(f"Missing {INDEX_PATH}. Run the crawler first.")

    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    items = index.get("items") or []
    if not isinstance(items, list):
        raise SystemExit("skills_index.json: expected `items` to be a list")

    by_id: dict[str, dict[str, Any]] = {}

    for it in items:
        if not isinstance(it, dict):
            continue
        full_id = _as_str(it.get("id")).strip()
        if not full_id:
            continue

        description_path = it.get("description")
        desc = _read_text_repo_relative(description_path)

        # Keep the payload small and query-friendly.
        by_id[full_id] = {
            "id": full_id,
            "providerId": it.get("providerId"),
            "source": it.get("source"),
            "skillId": it.get("skillId"),
            "title": it.get("title"),
            "link": it.get("link"),
            "firstSeenAt": it.get("firstSeenAt"),
            "installsAllTime": it.get("installsAllTime"),
            "installsTrending": it.get("installsTrending"),
            "installsHot": it.get("installsHot"),
            # Inline English description for searching.
            "description": desc,
            # Keep the path for debugging / refresh verification.
            "descriptionPath": description_path,
            "skillMdPath": it.get("skillMdPath"),
        }

    out = {
        "updatedAt": _utc_now_iso(),
        "sourceIndexUpdatedAt": index.get("updatedAt"),
        "version": 1,
        "count": len(by_id),
        "items": dict(sorted(by_id.items())),
    }

    OUTPUT_PATH.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(by_id)} skills)")


if __name__ == "__main__":
    main()

